// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjjjfzlvaowtdirwyksi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtqampmemx2YW93dGRpcnd5a3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4MTUyNTQsImV4cCI6MjA0OTM5MTI1NH0.5E24_bdNo8mt220tToiaTNiH-ARx1ePQpWS_MwytdA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);